// src/pages/Winner.jsx
import React, { useEffect, useState, useMemo, useCallback } from "react";
import { useParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import axios from "axios";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { Medal as MedalIcon } from "lucide-react";
import styles from "./Winner.module.css";

// ✅ IMPORTANT: use same key utils as TieSheet
import { sanitizeId, normalizeString } from "../components/TieSheet/bracketUtils";

/* ──────────────────────────────────────────────────────────────
   Utils
   ────────────────────────────────────────────────────────────── */
const getFullImageUrl = (filename) => {
  if (!filename) return "";
  if (filename.startsWith("http")) return filename;
  const cleanFilename = filename.replace(/^.*[\\/]/, "");
  const baseUrl = import.meta.env.VITE_API_URL || "http://localhost:5000";
  const uploadsUrl = baseUrl.replace(/\/api$/, "");
  return `${uploadsUrl}/uploads/${cleanFilename}?t=${Date.now()}`;
};

// ✅ Outcomes lookup that supports both RAW and SANITIZED bracket keys
const getOutcomesForKey = (allOutcomes, bracketKey) => {
  if (!allOutcomes || typeof allOutcomes !== "object") return {};
  if (!bracketKey) return {};
  return (
    allOutcomes[bracketKey] ||
    allOutcomes[sanitizeId(bracketKey)] ||
    {}
  );
};

/* ──────────────────────────────────────────────────────────────
   Header / Footer
   ────────────────────────────────────────────────────────────── */
const PageHeader = ({ tournamentName, federation, logoLeft, logoRight, age, gender }) => (
  <div className={styles.pageHeader}>
    {logoLeft && (
      <img
        src={logoLeft}
        alt="Logo Left"
        className={styles.logoLeft}
        onError={(e) => (e.target.style.display = "none")}
      />
    )}
    <div className={styles.headerContent}>
      <h1 className={styles.tournamentName}>{String(tournamentName || "").toUpperCase()}</h1>
      <p className={styles.federation}>{federation}</p>
      <h2 className={styles.medalTitle}>MEDAL WINNERS</h2>
      <h3 className={styles.ageGenderTitle}>
        {age} - {String(gender || "").toUpperCase()} Division
      </h3>
    </div>
    {logoRight && (
      <img
        src={logoRight}
        alt="Logo Right"
        className={styles.logoRight}
        onError={(e) => (e.target.style.display = "none")}
      />
    )}
  </div>
);

const PageFooter = ({ pageIdx, totalPages }) => (
  <div className={styles.pageFooter}>
    <div className={styles.footerContent}>
      <span className={styles.footerText}>
        Generated by EVOLVE - Tournament Manager | www.khiladi.com
      </span>
      <span className={styles.pageNumber}>
        Page {pageIdx + 1} of {totalPages} |{" "}
        {new Date().toLocaleString("en-US", {
          day: "numeric",
          month: "long",
          year: "numeric",
          hour: "2-digit",
          minute: "2-digit",
          hour12: true,
        })}
      </span>
    </div>
  </div>
);

/* ──────────────────────────────────────────────────────────────
   Main
   ────────────────────────────────────────────────────────────── */
const Winner = () => {
  const { id: rawId } = useParams();
  const id = rawId?.trim();
  const { token, isAuthenticated } = useAuth();

  const [tournament, setTournament] = useState(null);
  const [brackets, setBrackets] = useState([]);
  const [bracketsOutcomes, setBracketsOutcomes] = useState({});
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  if (!isAuthenticated) {
    window.location.href = "/login";
    return null;
  }

  useEffect(() => {
    const fetchData = async () => {
      try {
        setIsLoading(true);
        setError(null);

        const baseUrl = (import.meta.env.VITE_API_URL || "http://localhost:5000/api").replace(/\/+$/, "");
        const config = token ? { headers: { Authorization: `Bearer ${token}` } } : {};

        const tournamentRes = await axios.get(`${baseUrl}/tournament/${id}`, config);
        const td = tournamentRes.data;

        setTournament({
          name: td.tournamentName || "Unnamed Tournament",
          federation: td.federation || "N/A",
          logos: td.logos || [],
        });

        const tieSheetRes = await axios.get(`${baseUrl}/tournament/${id}/tiesheet`, config);
        const saved = tieSheetRes?.data?.tiesheet;

        if (saved?.brackets?.length) {
          setBrackets(saved.brackets);
          setBracketsOutcomes(saved.outcomes || {});
        } else {
          throw new Error("No tie-sheet generated yet.");
        }

        setIsLoading(false);
      } catch (err) {
        console.error(err);
        setError(err?.message || "Failed to load data");
        setIsLoading(false);
      }
    };

    if (id) fetchData();
  }, [id, token]);

  /**
   * ✅ Key idea:
   * Medal table should be per WEIGHT CATEGORY (baseKey) only.
   * For pooled categories: use PoolFinal bracket as representative.
   * For normal categories: use base bracket.
   */
  const displayBrackets = useMemo(() => {
    const list = Array.isArray(brackets) ? brackets : [];
    const byBase = new Map();

    for (const b of list) {
      if (!b?.key) continue;
      const baseKey = b.key.replace(/_Pool.*$/, "");

      const existing = byBase.get(baseKey);
      const isPoolFinal = b.key === `${baseKey}_PoolFinal`;

      if (!existing) {
        byBase.set(baseKey, b);
      } else {
        // prefer PoolFinal if present
        const existingBaseKey = existing.key.replace(/_Pool.*$/, "");
        const existingIsPoolFinal = existing.key === `${existingBaseKey}_PoolFinal`;
        if (!existingIsPoolFinal && isPoolFinal) {
          byBase.set(baseKey, b);
        }
      }
    }

    return Array.from(byBase.values());
  }, [brackets]);

  /* ────── Helper: resolve team/name (robust outcomes lookup) ────── */
  const getTeamName = useCallback((side, sideName, bracketKey, outcomes) => {
    if (!side) return { id: "", name: "", team: "" };

    if (side.team) {
      return {
        id: side.team.id || "",
        name: side.team.name || "TBD",
        team: side.team.team || "",
      };
    }

    if (side.sourceGame) {
      const sg = side.sourceGame;

      // outcomes for THIS bracketKey (raw or sanitized)
      let srcOutcomes = getOutcomesForKey(outcomes, bracketKey);

      // If PoolFinal and this side belongs to a pool, read that pool bracket outcomes instead
      if (bracketKey.endsWith("_PoolFinal") && side.pool) {
        const cat = bracketKey.replace("_PoolFinal", "");
        const poolKey = `${cat}_Pool${side.pool}`;
        srcOutcomes = getOutcomesForKey(outcomes, poolKey);
      }

      const prevWinner = srcOutcomes?.[sg.id];
      if (prevWinner) {
        return getTeamName(sg.sides[prevWinner], prevWinner, bracketKey, outcomes);
      }
      return { id: `tbd_${sg.id}_${sideName}`, name: "", team: "" };
    }

    return { id: "", name: "", team: "" };
  }, []);

  const getName = useCallback(
    (side, bracketKey, pool = null) => {
      if (!side) return "";
      if (side.team) return side.team.name || "";

      if (side.sourceGame) {
        const sg = side.sourceGame;

        let src = getOutcomesForKey(bracketsOutcomes, bracketKey);

        if (bracketKey.endsWith("_PoolFinal") && (pool || side.pool)) {
          const cat = bracketKey.replace("_PoolFinal", "");
          const poolKey = `${cat}_Pool${pool || side.pool}`;
          src = getOutcomesForKey(bracketsOutcomes, poolKey);
        }

        const w = src?.[sg.id];
        if (w) return getName(sg.sides[w], bracketKey, pool || side.pool);
      }

      return "";
    },
    [bracketsOutcomes]
  );

  /* ────── Medal extraction ────── */
  const getMedalWinners = useCallback(
    (bracket) => {
      const baseKey = bracket.key.replace(/_Pool.*$/, "");
      const poolFinal = brackets.find((b) => b?.key === `${baseKey}_PoolFinal`);
      const playerCount = bracket.categoryPlayerCount || bracket.playerCount;

      const blank = { name: "", team: "" };
      let gold = blank,
        silver = blank,
        bronze1 = blank,
        bronze2 = blank;

      // ✅ Pooled category: compute from PoolFinal
      if (poolFinal?.game) {
        const finalGame = poolFinal.game;
        const finalOut = getOutcomesForKey(bracketsOutcomes, poolFinal.key);
        const winSide = finalOut?.[finalGame.id];

        if (winSide) {
          const goldSide = finalGame.sides[winSide];
          const silverSide = finalGame.sides[winSide === "home" ? "away" : "home"];

          const goldInfo = getTeamName(goldSide, winSide, poolFinal.key, bracketsOutcomes);
          const silverInfo = getTeamName(
            silverSide,
            winSide === "home" ? "away" : "home",
            poolFinal.key,
            bracketsOutcomes
          );

          gold = { name: getName(goldSide, poolFinal.key, goldSide?.pool) || goldInfo.name, team: goldInfo.team };
          silver = {
            name: getName(silverSide, poolFinal.key, silverSide?.pool) || silverInfo.name,
            team: silverInfo.team,
          };
        }

        // Bronzes: pool semi-final losers (A/B) if 4+ in category
        if (playerCount >= 4) {
          ["A", "B"].forEach((p) => {
            const poolB = brackets.find((b) => b?.key === `${baseKey}_Pool${p}`);
            if (!poolB?.gamesByRound?.length) return;

            const semiRound = poolB.gamesByRound[poolB.gamesByRound.length - 2];
            const semi = semiRound?.[0];
            if (!semi) return;

            const semiOut = getOutcomesForKey(bracketsOutcomes, poolB.key);
            const win = semiOut?.[semi.id];
            if (!win) return;

            const loseSide = win === "home" ? "away" : "home";
            const loserInfo = getTeamName(semi.sides[loseSide], loseSide, poolB.key, bracketsOutcomes);
            const loser = { name: getName(semi.sides[loseSide], poolB.key) || loserInfo.name, team: loserInfo.team };

            if (p === "A") bronze1 = loser;
            else bronze2 = loser;
          });
        }

        return { gold, silver, bronze1, bronze2 };
      }

      // ✅ Single-elim category
      if (bracket?.game) {
        const out = getOutcomesForKey(bracketsOutcomes, baseKey);
        const finalGame = bracket.game;
        const winSide = out?.[finalGame.id];

        if (winSide) {
          const goldSide = finalGame.sides[winSide];
          const silverSide = finalGame.sides[winSide === "home" ? "away" : "home"];

          const goldInfo = getTeamName(goldSide, winSide, baseKey, bracketsOutcomes);
          const silverInfo = getTeamName(
            silverSide,
            winSide === "home" ? "away" : "home",
            baseKey,
            bracketsOutcomes
          );

          gold = { name: getName(goldSide, baseKey) || goldInfo.name, team: goldInfo.team };
          silver = { name: getName(silverSide, baseKey) || silverInfo.name, team: silverInfo.team };
        }

        // 3-player bronze
        if (playerCount === 3 && bracket.gamesByRound?.[0]?.[0]) {
          const first = bracket.gamesByRound[0][0];
          const win = out?.[first.id];
          if (win) {
            const loseSide = win === "home" ? "away" : "home";
            const info = getTeamName(first.sides[loseSide], loseSide, baseKey, bracketsOutcomes);
            bronze1 = { name: getName(first.sides[loseSide], baseKey) || info.name, team: info.team };
          }
        }
        // normal bronzes
        else if (playerCount >= 4 && bracket.gamesByRound?.length >= 2) {
          const semis = bracket.gamesByRound[bracket.gamesByRound.length - 2];
          if (semis?.length >= 2) {
            [0, 1].forEach((i) => {
              const semi = semis[i];
              const win = out?.[semi.id];
              if (!win) return;

              const loseSide = win === "home" ? "away" : "home";
              const info = getTeamName(semi.sides[loseSide], loseSide, baseKey, bracketsOutcomes);
              const loser = { name: getName(semi.sides[loseSide], baseKey) || info.name, team: info.team };

              if (i === 0) bronze1 = loser;
              else bronze2 = loser;
            });
          }
        }
      }

      return { gold, silver, bronze1, bronze2 };
    },
    [brackets, bracketsOutcomes, getName, getTeamName]
  );

  /* ────── Group by age + gender (using displayBrackets only) ────── */
  const grouped = useMemo(() => {
    const g = {};
    displayBrackets.forEach((b) => {
      const k = `${b.gender}_${b.ageCategory}`;
      if (!g[k]) g[k] = [];
      g[k].push(b);
    });

    // Sort weights stable (optional, no behavior risk)
    Object.keys(g).forEach((k) => {
      g[k].sort((a, b) => String(a.weightCategory || "").localeCompare(String(b.weightCategory || "")));
    });

    return g;
  }, [displayBrackets]);

  const hasWinners = useMemo(() => {
    return Object.values(grouped).some((group) =>
      group.some((b) => {
        const w = getMedalWinners(b);
        return w.gold.name || w.silver.name || w.bronze1.name || w.bronze2.name;
      })
    );
  }, [grouped, getMedalWinners]);

  /* ────── PDF Functions ────── */
  const generatePDFDoc = async () => {
    const pages = document.querySelectorAll(`.${styles.winnerPage}`);
    if (!pages.length) return null;

    const doc = new jsPDF("p", "mm", "a4");

    for (let i = 0; i < pages.length; i++) {
      if (i > 0) doc.addPage();

      const clone = pages[i].cloneNode(true);
      const container = document.createElement("div");
      Object.assign(container.style, {
        position: "absolute",
        left: "-9999px",
        width: "210mm",
        height: "297mm",
        background: "#fff",
      });
      container.appendChild(clone);
      document.body.appendChild(container);

      try {
        const canvas = await html2canvas(clone, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#fff",
          width: 794,
          height: 1123,
        });
        const img = canvas.toDataURL("image/png");
        doc.addImage(img, "PNG", 0, 0, 210, 297);
      } finally {
        document.body.removeChild(container);
      }
    }

    return doc;
  };

  const saveAllPDF = async () => {
    const doc = await generatePDFDoc();
    if (doc) doc.save(`Medal_Winners_${tournament?.name || "Tournament"}_${id}.pdf`);
  };

  const printAllPDF = async () => {
    const doc = await generatePDFDoc();
    if (doc) {
      const blob = doc.output("blob");
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank");
      setTimeout(() => {
        try {
          URL.revokeObjectURL(url);
        } catch {}
      }, 15000);
    }
  };

  /* ────── Render ────── */
  if (isLoading) {
    return (
      <div className={styles.loading}>
        <div>Loading medal winners...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.errorContainer}>
        <h2 className={styles.errorTitle}>Error Loading Winners</h2>
        <p className={styles.errorMessage}>{error}</p>
        <button className={styles.retryButton} onClick={() => window.location.reload()}>
          Retry
        </button>
        <button className={styles.backButton} onClick={() => window.history.back()}>
          Go Back
        </button>
      </div>
    );
  }

  const logoLeft = tournament?.logos?.[0] ? getFullImageUrl(tournament.logos[0]) : null;
  const logoRight = tournament?.logos?.[1] ? getFullImageUrl(tournament.logos[1]) : logoLeft;

  const medalIconCls = {
    Gold: styles.medalIconGold,
    Silver: styles.medalIconSilver,
    Bronze: styles.medalIconBronze,
  };

  return (
    <div className={styles.winnerContainer}>
      <div className={styles.buttonSection}>
        <div className={styles.pdfButtonWrapper}>
          <button onClick={printAllPDF} className={styles.printButton} disabled={!hasWinners}>
            Print
          </button>
          <button onClick={saveAllPDF} className={styles.pdfButton} disabled={!hasWinners}>
            Save PDF
          </button>
        </div>
      </div>

      {hasWinners ? (
        Object.entries(grouped).map(([key, catBrackets], catIdx) => {
          const [gender, age] = key.split("_");

          return (
            <div key={key} className={styles.winnerPage}>
              <PageHeader
                tournamentName={tournament?.name}
                federation={tournament?.federation}
                logoLeft={logoLeft}
                logoRight={logoRight}
                age={age}
                gender={gender}
              />

              <div className={styles.tableContainer}>
                <table className={styles.medalTable}>
                  <thead>
                    <tr>
                      <th className={styles.weightHeader}>Weight Category</th>
                      <th className={styles.medalHeader}>Medal</th>
                      <th className={styles.participantHeader}>Name</th>
                      <th className={styles.teamHeader}>Team</th>
                      <th className={styles.markHeader}>Mark</th>
                    </tr>
                  </thead>

                  <tbody>
                    {catBrackets.map((bracket) => {
                      const { gold, silver, bronze1, bronze2 } = getMedalWinners(bracket);
                      const playerCount = bracket.categoryPlayerCount || bracket.playerCount;
                      const rows = [];

                      if (gold.name) rows.push({ medal: "Gold", name: gold.name, team: gold.team });
                      if (silver.name) rows.push({ medal: "Silver", name: silver.name, team: silver.team });

                      if ((bronze1.name || bronze2.name) && playerCount >= 3) {
                        if (bronze1.name) rows.push({ medal: "Bronze", name: bronze1.name, team: bronze1.team });
                        if (bronze2.name && playerCount >= 4) rows.push({ medal: "Bronze", name: bronze2.name, team: bronze2.team });
                      }

                      if (!rows.length) {
                        return (
                          <tr key={`${bracket.key}-none`}>
                            <td className={styles.weightCell}>{bracket.weightCategory}</td>
                            <td colSpan={4} className={styles.noMedalCell}>
                              No results recorded yet
                            </td>
                          </tr>
                        );
                      }

                      return rows.map((r, i) => (
                        <tr key={`${bracket.key}-${r.medal}-${i}`}>
                          {i === 0 && (
                            <td rowSpan={rows.length} className={`${styles.weightCell} ${styles.weightCellFirst}`}>
                              {bracket.weightCategory}
                            </td>
                          )}

                          <td className={styles.medalCell}>
                            <div className={styles.medalContainer}>
                              <MedalIcon className={`${styles.medalIcon} ${medalIconCls[r.medal]}`} />
                              <span className={styles.medalText}>{r.medal}</span>
                            </div>
                          </td>

                          <td className={`${styles.participantCell} ${styles.winnerName}`}>
                            <strong>{r.name || "TBD"}</strong>
                          </td>

                          <td className={styles.teamCell}>
                            {r.team ? <span className={styles.teamName}>{r.team}</span> : <span className={styles.noTeam}>-</span>}
                          </td>

                          <td className={styles.markCell}></td>
                        </tr>
                      ));
                    })}
                  </tbody>
                </table>
              </div>

              <PageFooter pageIdx={catIdx} totalPages={Object.keys(grouped).length} />
            </div>
          );
        })
      ) : (
        <div className={styles.noWinnersContainer}>
          <MedalIcon className={styles.noWinnersIcon} />
          <h2 className={styles.noWinnersTitle}>No Winners Yet!</h2>
          <p className={styles.noWinnersText}>
            No tournament results have been recorded yet. Please complete the matches in the <strong>Tie Sheet</strong> section first.
          </p>
          <button className={styles.goToTieSheetButton} onClick={() => (window.location.href = `/tournaments/${id}/tiesheet`)}>
            Go to Tie Sheet
          </button>
        </div>
      )}
    </div>
  );
};

export default Winner;