import React, { useEffect, useState, useMemo, useCallback } from "react";
import { useParams } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import axios from "axios";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { Medal as MedalIcon } from "lucide-react";
import styles from "./Winner.module.css";

import { sanitizeId } from "../components/TieSheet/bracketUtils";

/* ──────────────────────────────────────────────────────────────
   Utils
   ────────────────────────────────────────────────────────────── */
const getFullImageUrl = (filename) => {
  if (!filename) return "";
  if (filename.startsWith("http")) return filename;
  const cleanFilename = filename.replace(/^.*[\\/]/, "");
  const baseUrl = import.meta.env.VITE_API_URL || "http://localhost:5000";
  const uploadsUrl = baseUrl.replace(/\/api$/, "");
  return `${uploadsUrl}/uploads/${cleanFilename}?t=${Date.now()}`;
};

const getOutcomesForKey = (allOutcomes, bracketKey) => {
  if (!allOutcomes || typeof allOutcomes !== "object") return {};
  if (!bracketKey) return {};
  return allOutcomes[bracketKey] || allOutcomes[sanitizeId(bracketKey)] || {};
};

const getFinalGame = (bracket) => {
  if (bracket?.gamesByRound?.length > 0) {
    return bracket.gamesByRound[bracket.gamesByRound.length - 1]?.[0] || null;
  }
  if (bracket?.game) return bracket.game;
  return null;
};

const getSemiFinalGames = (bracket) => {
  if (bracket?.gamesByRound?.length >= 2) {
    return bracket.gamesByRound[bracket.gamesByRound.length - 2] || [];
  }
  return [];
};

/**
 * Supports multiple saved outcome shapes:
 * 1) { "3": "home" }
 * 2) { 3: "away" }
 * 3) { "game_3": "home" }
 * 4) { "3": { winner: "home" } }
 * 5) { "game_3": { winner: "away" } }
 */
const getWinnerSide = (outcomesObj, gameId) => {
  if (!outcomesObj || typeof outcomesObj !== "object" || gameId === undefined || gameId === null) {
    return null;
  }

  const candidates = [
    outcomesObj[gameId],
    outcomesObj[String(gameId)],
    outcomesObj[`game_${gameId}`],
    outcomesObj[gameId]?.winner,
    outcomesObj[String(gameId)]?.winner,
    outcomesObj[`game_${gameId}`]?.winner,
  ];

  const found = candidates.find((value) => value === "home" || value === "away");
  return found || null;
};

/* ──────────────────────────────────────────────────────────────
   Header / Footer
   ────────────────────────────────────────────────────────────── */
const PageHeader = ({ tournamentName, federation, logoLeft, logoRight, age, gender }) => (
  <div className={styles.pageHeader}>
    {logoLeft && (
      <img
        src={logoLeft}
        alt="Logo Left"
        className={styles.logoLeft}
        onError={(e) => (e.target.style.display = "none")}
      />
    )}
    <div className={styles.headerContent}>
      <h1 className={styles.tournamentName}>{String(tournamentName || "").toUpperCase()}</h1>
      <p className={styles.federation}>{federation}</p>
      <h2 className={styles.medalTitle}>MEDAL WINNERS</h2>
      <h3 className={styles.ageGenderTitle}>
        {age} - {String(gender || "").toUpperCase()} Division
      </h3>
    </div>
    {logoRight && (
      <img
        src={logoRight}
        alt="Logo Right"
        className={styles.logoRight}
        onError={(e) => (e.target.style.display = "none")}
      />
    )}
  </div>
);

const PageFooter = ({ pageIdx, totalPages }) => (
  <div className={styles.pageFooter}>
    <div className={styles.footerContent}>
      <span className={styles.footerText}>
        Generated by EVOLVE - Tournament Manager | www.khiladi.com
      </span>
      <span className={styles.pageNumber}>
        Page {pageIdx + 1} of {totalPages} |{" "}
        {new Date().toLocaleString("en-US", {
          day: "numeric",
          month: "long",
          year: "numeric",
          hour: "2-digit",
          minute: "2-digit",
          hour12: true,
        })}
      </span>
    </div>
  </div>
);

/* ──────────────────────────────────────────────────────────────
   Main
   ────────────────────────────────────────────────────────────── */
const Winner = () => {
  const { id: rawId } = useParams();
  const id = rawId?.trim();
  const { token, isAuthenticated } = useAuth();

  const [tournament, setTournament] = useState(null);
  const [brackets, setBrackets] = useState([]);
  const [bracketsOutcomes, setBracketsOutcomes] = useState({});
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  if (!isAuthenticated) {
    window.location.href = "/login";
    return null;
  }

  useEffect(() => {
    const fetchData = async () => {
      try {
        setIsLoading(true);
        setError(null);

        const rawBase = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
        const baseUrl = rawBase.replace(/\/+$/, "");
        const config = token ? { headers: { Authorization: `Bearer ${token}` } } : {};

        const tournamentRes = await axios.get(`${baseUrl}/tournament/${id}`, config);
        const td = tournamentRes.data;

        setTournament({
          name: td.tournamentName || "Unnamed Tournament",
          federation: td.federation || "N/A",
          logos: td.logos || [],
        });

        const [tieSheetRes, outcomesRes] = await Promise.allSettled([
          axios.get(`${baseUrl}/tournament/${id}/tiesheet`, config),
          axios.get(`${baseUrl}/tournament/${id}/tiesheet-outcomes`, config),
        ]);

        let savedTieSheet = null;
        let liveOutcomes = {};

        if (tieSheetRes.status === "fulfilled") {
          savedTieSheet = tieSheetRes.value?.data?.tiesheet || null;
        }

        if (outcomesRes.status === "fulfilled") {
          liveOutcomes = outcomesRes.value?.data?.outcomes || {};
        }

        if (savedTieSheet?.brackets?.length) {
          setBrackets(savedTieSheet.brackets);

          const finalOutcomes =
            liveOutcomes && Object.keys(liveOutcomes).length > 0
              ? liveOutcomes
              : savedTieSheet.outcomes || {};

          setBracketsOutcomes(finalOutcomes);
        } else {
          throw new Error("No tie-sheet generated yet.");
        }

        setIsLoading(false);
      } catch (err) {
        console.error("Winner page load failed:", err);
        setError(err?.message || "Failed to load data");
        setIsLoading(false);
      }
    };

    if (id) fetchData();
  }, [id, token]);

  /**
   * Show only one bracket per weight category:
   * - If pooled category exists, prefer PoolFinal
   * - Else use normal base bracket
   */
  const displayBrackets = useMemo(() => {
    const list = Array.isArray(brackets) ? brackets : [];
    const byBase = new Map();

    for (const b of list) {
      if (!b?.key) continue;
      const baseKey = b.key.replace(/_Pool.*$/, "");

      const existing = byBase.get(baseKey);
      const isPoolFinal = b.key === `${baseKey}_PoolFinal`;

      if (!existing) {
        byBase.set(baseKey, b);
      } else {
        const existingBaseKey = existing.key.replace(/_Pool.*$/, "");
        const existingIsPoolFinal = existing.key === `${existingBaseKey}_PoolFinal`;
        if (!existingIsPoolFinal && isPoolFinal) {
          byBase.set(baseKey, b);
        }
      }
    }

    return Array.from(byBase.values());
  }, [brackets]);

  const getName = useCallback(
    (side, bracketKey, pool = null) => {
      if (!side) return "";
      if (side.team) return side.team.name || "";

      if (side.sourceGame) {
        const sg = side.sourceGame;

        let src = getOutcomesForKey(bracketsOutcomes, bracketKey);

        if (bracketKey.endsWith("_PoolFinal") && (pool || side.pool)) {
          const cat = bracketKey.replace("_PoolFinal", "");
          const poolKey = `${cat}_Pool${pool || side.pool}`;
          src = getOutcomesForKey(bracketsOutcomes, poolKey);
        }

        const winnerSide = getWinnerSide(src, sg.id);
        if (winnerSide) {
          return getName(sg.sides?.[winnerSide], bracketKey, pool || side.pool);
        }
      }

      return "";
    },
    [bracketsOutcomes]
  );

  const getTeamName = useCallback((side, sideName, bracketKey, outcomes) => {
    if (!side) return { id: "", name: "", team: "" };

    if (side.team) {
      return {
        id: side.team.id || "",
        name: side.team.name || "TBD",
        team: side.team.team || "",
      };
    }

    if (side.sourceGame) {
      const sg = side.sourceGame;

      let srcOutcomes = getOutcomesForKey(outcomes, bracketKey);

      if (bracketKey.endsWith("_PoolFinal") && side.pool) {
        const cat = bracketKey.replace("_PoolFinal", "");
        const poolKey = `${cat}_Pool${side.pool}`;
        srcOutcomes = getOutcomesForKey(outcomes, poolKey);
      }

      const prevWinner = getWinnerSide(srcOutcomes, sg.id);
      if (prevWinner) {
        return getTeamName(sg.sides?.[prevWinner], prevWinner, bracketKey, outcomes);
      }

      return { id: `tbd_${sg.id}_${sideName}`, name: "", team: "" };
    }

    return { id: "", name: "", team: "" };
  }, []);

  const getMedalWinners = useCallback(
    (bracket) => {
      const baseKey = bracket.key.replace(/_Pool.*$/, "");
      const poolFinal = brackets.find((b) => b?.key === `${baseKey}_PoolFinal`);
      const playerCount = bracket.categoryPlayerCount || bracket.playerCount;

      const blank = { name: "", team: "" };
      let gold = blank;
      let silver = blank;
      let bronze1 = blank;
      let bronze2 = blank;

      // ✅ Pooled category
      if (poolFinal) {
        const finalGame = getFinalGame(poolFinal);
        const finalOut = getOutcomesForKey(bracketsOutcomes, poolFinal.key);
        const winSide = finalGame ? getWinnerSide(finalOut, finalGame.id) : null;

        if (finalGame && (winSide === "home" || winSide === "away")) {
          const goldSide = finalGame.sides?.[winSide];
          const silverSide = finalGame.sides?.[winSide === "home" ? "away" : "home"];

          const goldInfo = getTeamName(goldSide, winSide, poolFinal.key, bracketsOutcomes);
          const silverInfo = getTeamName(
            silverSide,
            winSide === "home" ? "away" : "home",
            poolFinal.key,
            bracketsOutcomes
          );

          gold = {
            name: getName(goldSide, poolFinal.key, goldSide?.pool) || goldInfo.name,
            team: goldInfo.team,
          };

          silver = {
            name: getName(silverSide, poolFinal.key, silverSide?.pool) || silverInfo.name,
            team: silverInfo.team,
          };
        }

        if (playerCount >= 4) {
          ["A", "B"].forEach((p) => {
            const poolBracket = brackets.find((b) => b?.key === `${baseKey}_Pool${p}`);
            if (!poolBracket) return;

            const semis = getSemiFinalGames(poolBracket);
            const semi = semis?.[0];
            if (!semi) return;

            const semiOutcomes = getOutcomesForKey(bracketsOutcomes, poolBracket.key);
            const semiWinner = getWinnerSide(semiOutcomes, semi.id);

            if (semiWinner === "home" || semiWinner === "away") {
              const loseSide = semiWinner === "home" ? "away" : "home";
              const loserInfo = getTeamName(
                semi.sides?.[loseSide],
                loseSide,
                poolBracket.key,
                bracketsOutcomes
              );

              const loser = {
                name: getName(semi.sides?.[loseSide], poolBracket.key) || loserInfo.name,
                team: loserInfo.team,
              };

              if (p === "A") bronze1 = loser;
              else bronze2 = loser;
            }
          });
        }

        return { gold, silver, bronze1, bronze2 };
      }

      // ✅ Single elimination
      const finalGame = getFinalGame(bracket);
      const out = getOutcomesForKey(bracketsOutcomes, baseKey);
      const winSide = finalGame ? getWinnerSide(out, finalGame.id) : null;

      if (playerCount === 1) {
        const singleSide =
          finalGame?.sides?.home?.team
            ? finalGame.sides.home
            : finalGame?.sides?.away?.team
            ? finalGame.sides.away
            : null;

        if (singleSide) {
          const info = getTeamName(singleSide, "home", baseKey, bracketsOutcomes);
          gold = {
            name: getName(singleSide, baseKey) || info.name,
            team: info.team,
          };
        }

        return { gold, silver, bronze1, bronze2 };
      }

      if (finalGame && (winSide === "home" || winSide === "away")) {
        const goldSide = finalGame.sides?.[winSide];
        const silverSide = finalGame.sides?.[winSide === "home" ? "away" : "home"];

        const goldInfo = getTeamName(goldSide, winSide, baseKey, bracketsOutcomes);
        const silverInfo = getTeamName(
          silverSide,
          winSide === "home" ? "away" : "home",
          baseKey,
          bracketsOutcomes
        );

        gold = {
          name: getName(goldSide, baseKey) || goldInfo.name,
          team: goldInfo.team,
        };

        silver = {
          name: getName(silverSide, baseKey) || silverInfo.name,
          team: silverInfo.team,
        };
      }

      if (playerCount === 3) {
        const firstRound = bracket.gamesByRound?.[0]?.[0];
        const firstWinner = firstRound ? getWinnerSide(out, firstRound.id) : null;

        if (firstRound && (firstWinner === "home" || firstWinner === "away")) {
          const loseSide = firstWinner === "home" ? "away" : "home";
          const info = getTeamName(firstRound.sides?.[loseSide], loseSide, baseKey, bracketsOutcomes);
          bronze1 = {
            name: getName(firstRound.sides?.[loseSide], baseKey) || info.name,
            team: info.team,
          };
        }
      } else if (playerCount >= 4) {
        const semis = getSemiFinalGames(bracket);

        if (semis?.length >= 1) {
          const semi1 = semis[0];
          const semi1Winner = getWinnerSide(out, semi1.id);

          if (semi1 && (semi1Winner === "home" || semi1Winner === "away")) {
            const loseSide = semi1Winner === "home" ? "away" : "home";
            const info = getTeamName(semi1.sides?.[loseSide], loseSide, baseKey, bracketsOutcomes);
            bronze1 = {
              name: getName(semi1.sides?.[loseSide], baseKey) || info.name,
              team: info.team,
            };
          }

          if (semis.length >= 2) {
            const semi2 = semis[1];
            const semi2Winner = getWinnerSide(out, semi2.id);

            if (semi2 && (semi2Winner === "home" || semi2Winner === "away")) {
              const loseSide = semi2Winner === "home" ? "away" : "home";
              const info = getTeamName(semi2.sides?.[loseSide], loseSide, baseKey, bracketsOutcomes);
              bronze2 = {
                name: getName(semi2.sides?.[loseSide], baseKey) || info.name,
                team: info.team,
              };
            }
          }
        }
      }

      return { gold, silver, bronze1, bronze2 };
    },
    [brackets, bracketsOutcomes, getName, getTeamName]
  );

  const grouped = useMemo(() => {
    const g = {};
    displayBrackets.forEach((b) => {
      const k = `${b.gender}_${b.ageCategory}`;
      if (!g[k]) g[k] = [];
      g[k].push(b);
    });

    Object.keys(g).forEach((k) => {
      g[k].sort((a, b) => String(a.weightCategory || "").localeCompare(String(b.weightCategory || "")));
    });

    return g;
  }, [displayBrackets]);

  const hasWinners = useMemo(() => {
    return Object.values(grouped).some((group) =>
      group.some((b) => {
        const w = getMedalWinners(b);
        return w.gold.name || w.silver.name || w.bronze1.name || w.bronze2.name;
      })
    );
  }, [grouped, getMedalWinners]);

  const generatePDFDoc = async () => {
    const pages = document.querySelectorAll(`.${styles.winnerPage}`);
    if (!pages.length) return null;

    const doc = new jsPDF("p", "mm", "a4");

    for (let i = 0; i < pages.length; i++) {
      if (i > 0) doc.addPage();

      const clone = pages[i].cloneNode(true);
      const container = document.createElement("div");
      Object.assign(container.style, {
        position: "absolute",
        left: "-9999px",
        width: "210mm",
        height: "297mm",
        background: "#fff",
      });
      container.appendChild(clone);
      document.body.appendChild(container);

      try {
        const canvas = await html2canvas(clone, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#fff",
          width: 794,
          height: 1123,
        });
        const img = canvas.toDataURL("image/png");
        doc.addImage(img, "PNG", 0, 0, 210, 297);
      } finally {
        document.body.removeChild(container);
      }
    }

    return doc;
  };

  const saveAllPDF = async () => {
    const doc = await generatePDFDoc();
    if (doc) doc.save(`Medal_Winners_${tournament?.name || "Tournament"}_${id}.pdf`);
  };

  const printAllPDF = async () => {
    const doc = await generatePDFDoc();
    if (doc) {
      const blob = doc.output("blob");
      const url = URL.createObjectURL(blob);
      window.open(url, "_blank");
      setTimeout(() => {
        try {
          URL.revokeObjectURL(url);
        } catch {}
      }, 15000);
    }
  };

  if (isLoading) {
    return (
      <div className={styles.loading}>
        <div>Loading medal winners...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.errorContainer}>
        <h2 className={styles.errorTitle}>Error Loading Winners</h2>
        <p className={styles.errorMessage}>{error}</p>
        <button className={styles.retryButton} onClick={() => window.location.reload()}>
          Retry
        </button>
        <button className={styles.backButton} onClick={() => window.history.back()}>
          Go Back
        </button>
      </div>
    );
  }

  const logoLeft = tournament?.logos?.[0] ? getFullImageUrl(tournament.logos[0]) : null;
  const logoRight = tournament?.logos?.[1] ? getFullImageUrl(tournament.logos[1]) : logoLeft;

  const medalIconCls = {
    Gold: styles.medalIconGold,
    Silver: styles.medalIconSilver,
    Bronze: styles.medalIconBronze,
  };

  return (
    <div className={styles.winnerContainer}>
      <div className={styles.buttonSection}>
        <div className={styles.pdfButtonWrapper}>
          <button onClick={printAllPDF} className={styles.printButton} disabled={!hasWinners}>
            Print
          </button>
          <button onClick={saveAllPDF} className={styles.pdfButton} disabled={!hasWinners}>
            Save PDF
          </button>
        </div>
      </div>

      {hasWinners ? (
        Object.entries(grouped).map(([key, catBrackets], catIdx) => {
          const [gender, age] = key.split("_");

          return (
            <div key={key} className={styles.winnerPage}>
              <PageHeader
                tournamentName={tournament?.name}
                federation={tournament?.federation}
                logoLeft={logoLeft}
                logoRight={logoRight}
                age={age}
                gender={gender}
              />

              <div className={styles.tableContainer}>
                <table className={styles.medalTable}>
                  <thead>
                    <tr>
                      <th className={styles.weightHeader}>Weight Category</th>
                      <th className={styles.medalHeader}>Medal</th>
                      <th className={styles.participantHeader}>Name</th>
                      <th className={styles.teamHeader}>Team</th>
                      <th className={styles.markHeader}>Mark</th>
                    </tr>
                  </thead>

                  <tbody>
                    {catBrackets.map((bracket) => {
                      const { gold, silver, bronze1, bronze2 } = getMedalWinners(bracket);
                      const playerCount = bracket.categoryPlayerCount || bracket.playerCount;
                      const rows = [];

                      if (gold.name) rows.push({ medal: "Gold", name: gold.name, team: gold.team });
                      if (silver.name) rows.push({ medal: "Silver", name: silver.name, team: silver.team });

                      if ((bronze1.name || bronze2.name) && playerCount >= 3) {
                        if (bronze1.name) rows.push({ medal: "Bronze", name: bronze1.name, team: bronze1.team });
                        if (bronze2.name && playerCount >= 4) {
                          rows.push({ medal: "Bronze", name: bronze2.name, team: bronze2.team });
                        }
                      }

                      if (!rows.length) {
                        return (
                          <tr key={`${bracket.key}-none`}>
                            <td className={styles.weightCell}>{bracket.weightCategory}</td>
                            <td colSpan={4} className={styles.noMedalCell}>
                              No results recorded yet
                            </td>
                          </tr>
                        );
                      }

                      return rows.map((r, i) => (
                        <tr key={`${bracket.key}-${r.medal}-${i}`}>
                          {i === 0 && (
                            <td rowSpan={rows.length} className={`${styles.weightCell} ${styles.weightCellFirst}`}>
                              {bracket.weightCategory}
                            </td>
                          )}

                          <td className={styles.medalCell}>
                            <div className={styles.medalContainer}>
                              <MedalIcon className={`${styles.medalIcon} ${medalIconCls[r.medal]}`} />
                              <span className={styles.medalText}>{r.medal}</span>
                            </div>
                          </td>

                          <td className={`${styles.participantCell} ${styles.winnerName}`}>
                            <strong>{r.name || "TBD"}</strong>
                          </td>

                          <td className={styles.teamCell}>
                            {r.team ? (
                              <span className={styles.teamName}>{r.team}</span>
                            ) : (
                              <span className={styles.noTeam}>-</span>
                            )}
                          </td>

                          <td className={styles.markCell}></td>
                        </tr>
                      ));
                    })}
                  </tbody>
                </table>
              </div>

              <PageFooter pageIdx={catIdx} totalPages={Object.keys(grouped).length} />
            </div>
          );
        })
      ) : (
        <div className={styles.noWinnersContainer}>
          <MedalIcon className={styles.noWinnersIcon} />
          <h2 className={styles.noWinnersTitle}>No Winners Yet!</h2>
          <p className={styles.noWinnersText}>
            No tournament results have been recorded yet. Please complete the matches in the <strong>Tie Sheet</strong> section first.
          </p>
          <button
            className={styles.goToTieSheetButton}
            onClick={() => (window.location.href = `/tournaments/${id}/tiesheet`)}
          >
            Go to Tie Sheet
          </button>
        </div>
      )}
    </div>
  );
};

export default Winner;